# Configuration for eufy-security-ws setup

# Name of the big-bear-eufy-security-ws application
name: big-bear-eufy-security-ws
# Service definitions for the big-bear-eufy-security-ws application
services:
  # Service name: big-bear-eufy-security-ws
  # The `big-bear-eufy-security-ws` service definition
  big-bear-eufy-security-ws:
    # Name of the container
    container_name: big-bear-eufy-security-ws
    # Image to be used for the container
    image: bropat/eufy-security-ws:1.9.9
    # Environment variables for the container
    environment:
      USERNAME: "[EUFY_USERNAME]"
      PASSWORD: "[EUFY_PASSWORD]"
      COUNTRY: "US"
      LANGUAGE: "en"
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local data directory to /data inside the container
      - /DATA/AppData/$AppID/data:/data
    # Network configuration
    network_mode: host
    x-casaos:
      envs:
        - container: USERNAME
          description:
            en_us: 'Container Variable: USERNAME'
        - container: PASSWORD
          description:
            en_us: 'Container Variable: PASSWORD'
        - container: COUNTRY
          description:
            en_us: 'Container Variable: COUNTRY'
        - container: LANGUAGE
          description:
            en_us: 'Container Variable: LANGUAGE'
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Main service for this application
  main: big-bear-eufy-security-ws
  # Detailed description for the application
  description:
    en_us: eufy-security-ws is a small server wrapper around the eufy-security-client library to access it via a WebSocket. It allows you to control Eufy security devices by connecting to the Eufy cloud servers and local/remote stations.
  # Brief tagline for the application
  tagline:
    en_us: eufy-security-ws
  # Developer's information
  developer: bropat
  # Author of this particular configuration
  author: BigBearTechWorld
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/_example/logo.jpg
  # Thumbnail image for the application (if any)
  thumbnail: ""
  # Installation tips
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-eufy-security-ws-to-bigbearcasaos/2228
  # Title for the application
  title:
    en_us: Eufy Security WS
  # Category under which the application falls
  category: BigBearCasaOS
  # Default port mapping for the application
  port_map: "3000"
