# Configuration for cyberchef setup

# Name of the big-bear-cyberchef application
name: big-bear-cyberchef
# Service definitions for the big-bear-cyberchef application
services:
  # Service name: big-bear-cyberchef
  # The `big-bear-cyberchef` service definition
  big-bear-cyberchef:
    # Name of the container
    container_name: big-bear-cyberchef
    # Image to be used for the container
    image: ghcr.io/gchq/cyberchef:10.22.0
    # Container restart policy
    restart: unless-stopped
    # Ports mapping between host and container
    ports:
      # Mapping port 8080 of the host to port 80 of the container
      - "8080:80"
    x-casaos:
      ports:
        - container: "80"
          description:
            en_us: 'Container Port: 80'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Main service for this application
  main: big-bear-cyberchef
  # Detailed description for the application
  description:
    en_us: CyberChef is a simple, intuitive web app for carrying out all manner of cyber operations within a web browser. These operations include simple encoding like XOR and Base64, more complex encryption like AES, DES and Blowfish, creating binary and hexdumps, compression and decompression of data, calculating hashes and checksums, IPv6 and X.509 parsing, changing character encodings, and much more.
  # Brief tagline for the application
  tagline:
    en_us: The Cyber Swiss Army Knife
  # Developer's information
  developer: gchq
  # Author of this particular configuration
  author: BigBearTechWorld
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/cyberchef.png
  # Thumbnail image for the application (if any)
  thumbnail: ""
  # Title for the application
  title:
    en_us: CyberChef
  # Category under which the application falls
  category: BigBearCasaOS
  # Default port mapping for the application
  port_map: "8080"
