# Configuration for matterbridge setup

# Application Name
name: big-bear-matterbridge
# Services used in the application
services:
  # The `big-bear-matterbridge` service for the Matterbridge application
  big-bear-matterbridge:
    # Name of the container
    container_name: big-bear-matterbridge
    # Docker image to be used
    image: luligu/matterbridge:3.5.0
    # Restart policy for the service
    restart: unless-stopped
    # Network mode set to host for Matter mdns support
    network_mode: host
    # Volume mappings for persistent storage
    volumes:
      - /DATA/AppData/$AppID/Matterbridge:/root/Matterbridge
      - /DATA/AppData/$AppID/.matterbridge:/root/.matterbridge
    x-casaos:
      volumes:
        - container: /root/Matterbridge
          description:
            en_us: 'Container Path: /root/Matterbridge'
        - container: /root/.matterbridge
          description:
            en_us: 'Container Path: /root/.matterbridge'
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
    - arm64
  # Main service for this application
  main: big-bear-matterbridge
  # Detailed description for the application
  description:
    en_us: Matterbridge is a Matter plugin manager that allows you to have all your Matter devices up and running in a couple of minutes without having to deal with the pairing process for each individual device. It creates a device that can be paired with any ecosystem, such as Apple Home, Google Home, Amazon Alexa, Home Assistant, or any other platform supporting Matter.
  # Brief tagline for the application
  tagline:
    en_us: Matter plugin manager for smart home devices
  # Developer's information
  developer: Luligu
  # Author of this particular configuration
  author: BigBearTechWorld
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/matterbridge.png
  # Thumbnail image for the application (if any)
  thumbnail: ""
  # Installation tips
  tips:
    before_install:
      en_us: |
        Before you install read this: https://community.bigbeartechworld.com/t/added-matterbridge-to-bigbearcasaos/5072#p-7704-documentation-2
  # Title for the application
  title:
    en_us: Matterbridge
  # Category under which the application falls
  category: BigBearCasaOS
  # Default port mapping for the application
  port_map: "8283"
